Controllers/OwnerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using RB_PetHotel.Data;
using RB_PetHotel.Models;
using System.Data;

namespace RB_PetHotel.Controllers
{
    [Authorize(Roles = "User, Admin")]
    public class OwnerController : Controller
    {
        private Repository.OwnerRepository _repository;
        public OwnerController (ApplicationDbContext dbContext)
        {
            _repository = new Repository.OwnerRepository (dbContext);
        }
        // GET: OwnerController
        public ActionResult Index()
        {
            var owners = _repository.GetAllOwners();
            return View("Index", owners);
        }

        // GET: OwnerController/Details/5
        public ActionResult Details(Guid id)
        {
            var model = _repository.GetOwnerByID(id);
            return View("DetailsOwner", model);
        }

        // GET: OwnerController/Create
        public ActionResult Create()
        {
            var model = new OwnerModel();
            if (User.Identity.IsAuthenticated)
            {
                model.OwnerName = User.Identity.Name;
            }
            return View("CreateOwner", model);
        }

        // POST: OwnerController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                Models.OwnerModel ownerModel = new Models.OwnerModel ();
                var task = TryUpdateModelAsync(ownerModel);
                task.Wait();
                if (task.Result)
                {
                    _repository.InsertOwner(ownerModel);
                }
                return View("CreateOwner");
                //return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View("CreateOwner");
                //return View();
            }

        }

        // GET: OwnerController/Edit/5
        public ActionResult Edit(Guid id)
        {
            var model = _repository.GetOwnerByID(id);
            return View("EditOwner", model);
        }

        // POST: OwnerController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                var ownerModel = new OwnerModel();
                var task = TryUpdateModelAsync(ownerModel);
                task.Wait();
                if (task.Result)
                {
                    _repository.UpdateOwner(ownerModel);
                    return RedirectToAction("Index");
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }

        // GET: OwnerController/Delete/5
        public ActionResult Delete(Guid id)
        {
            var model = _repository.GetOwnerByID(id);
            return View("DeleteOwner", model);
        }

        // POST: OwnerController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Guid id, IFormCollection collection)
        {
            try
            {
                _repository.DeleteOwner(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View("DeleteOwner", id);
            }
        }
    }
}

Controllers/PetController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using RB_PetHotel.Data;
using RB_PetHotel.Models;
using System.Data;

namespace RB_PetHotel.Controllers
{
    [Authorize(Roles = "User, Admin")]
    public class PetController : Controller
    {
        private Repository.PetRepository _repository;
        public PetController(ApplicationDbContext dbContext)
        {
            _repository= new Repository.PetRepository(dbContext);
        }

        // GET: PetController
        public ActionResult Index()
        {
            var pets = _repository.GetAllPets();
            return View("Index", pets);
        }

        // GET: PetController/Details/5
        public ActionResult Details(Guid id)
        {
            var model = _repository.GetPetByID(id);
            return View("DetailsPet", model);
        }

        // GET: PetController/Create
        public ActionResult Create()
        {
            return View("CreatePet");
        }

        // POST: PetController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                Models.PetModel petModel = new Models.PetModel();
                var task = TryUpdateModelAsync(petModel);
                task.Wait();
                if (task.Result)
                {
                    _repository.InsertPet(petModel);
                }
                return View("CreatePet");
            }
            catch
            {
                return View("CreatePet");
            }
        }

        // GET: PetController/Edit/5
        public ActionResult Edit(Guid id)
        {
            var model = _repository.GetPetByID(id);
            return View("EditPet", model);
        }

        // POST: PetController/Edit/5 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                var petModel = new PetModel();
                var task = TryUpdateModelAsync(petModel);
                task.Wait();
                if (task.Result)
                {
                    _repository.UpdatePet(petModel);
                    return RedirectToAction("Index");
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }

        // GET: PetController/Delete/5
        public ActionResult Delete(Guid id)
        {
            var model = _repository.GetPetByID(id);
            return View("DeletePet", model);
        }

        // POST: PetController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Guid id, IFormCollection collection)
        {
            try
            {
                
                _repository.DeletePet(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View("DeletePet", id);
            }
        }
    }
}

Controllers/PetRoomController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using RB_PetHotel.Data;
using RB_PetHotel.Models;
using System.Data;

namespace RB_PetHotel.Controllers
{
    [Authorize(Roles = "Admin")]
    public class PetRoomController : Controller
    {
        private Repository.PetRoomRepository _repository;
        public PetRoomController(ApplicationDbContext dbContext)
        {
            _repository = new Repository.PetRoomRepository(dbContext);
        }

        // GET: PetRoomController
        public ActionResult Index()
        {
            var petrooms = _repository.GetAllPetRooms(); 
            return View("Index", petrooms);
        }

        // GET: PetRoomController/Details/5
        public ActionResult Details(Guid id)
        {
            var model = _repository.GetPetRoomByID(id);
            return View("DetailsPetRoom", model);
        }

        // GET: PetRoomController/Create
        public ActionResult Create()
        {
            return View("CreatePetRoom");
        }

        // POST: PetRoomController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                Models.PetRoomModel petRoomModel= new Models.PetRoomModel();

                var task = TryUpdateModelAsync(petRoomModel);
                task.Wait();
                if (task.Result)
                {
                    _repository.InsertPetRoom(petRoomModel);
                }
                return View("CreatePetRoom");
            }
            catch
            {
                return View("CreatePetRoom");
            }
        }

        // GET: PetRoomController/Edit/5
        public ActionResult Edit(Guid id)
        {
            var model = _repository.GetPetRoomByID(id);
            return View("EditPetRoom", model);
        }

        // POST: PetRoomController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                var petRoomModel = new PetRoomModel();
                var task = TryUpdateModelAsync(petRoomModel);
                task.Wait();
                if (task.Result)
                {
                    _repository.UpdatePetRoom(petRoomModel);
                    return RedirectToAction("Index");
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }

        // GET: PetRoomController/Delete/5
        public ActionResult Delete(Guid id)
        {
            var model = _repository.GetPetRoomByID(id);
            return View("DeletePetRoom", model);
        }

        // POST: PetRoomController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Guid id, IFormCollection collection)
        {
            try
            {
                _repository.DeletePetRoom(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View("DeletePetRoom", id);
            }
        }
    }
}

Controllers/RoomController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using NuGet.Protocol.Core.Types;
using RB_PetHotel.Data;
using RB_PetHotel.Models;
using System.Data;

namespace RB_PetHotel.Controllers
{
    public class RoomController : Controller
    {

        private Repository.RoomRepository _repository;
        public RoomController(ApplicationDbContext dbContext)
        {
            _repository = new Repository.RoomRepository(dbContext);
        }
        // GET: RoomController
        public ActionResult Index()
        {
            var rooms = _repository.GetAllRooms();
            return View("Index", rooms);
        }

        // GET: RoomController/Details/5
        public ActionResult Details(Guid id)
        {
            var model = _repository.GetRoomByID(id);
            return View("DetailsRoom", model);
        }

        // GET: RoomController/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View("CreateRoom");
        }

        // POST: RoomController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                Models.RoomModel roomModel = new Models.RoomModel();
                
                var task = TryUpdateModelAsync(roomModel);
                task.Wait();
                if (task.Result)
                {
                    _repository.InsertRoom(roomModel);
                }
                return View("CreateRoom");
            }
            catch
            {
                return View("CreateRoom");
            }
        }

        // GET: RoomController/Edit/5
        public ActionResult Edit(Guid id)
        {
            var model = _repository.GetRoomByID(id);
            return View("EditRoom", model);
        }

        // POST: RoomController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                var roomModel = new RoomModel();

                var task = TryUpdateModelAsync(roomModel);
                task.Wait();
                if (task.Result)
                {
                    _repository.UpdateRoom(roomModel);
                    return RedirectToAction("Index");
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }

        // GET: RoomController/Delete/5
        public ActionResult Delete(Guid id)
        {
            var model = _repository.GetRoomByID(id);
            return View("DeleteRoom", model);
        }

        // POST: RoomController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Guid id, IFormCollection collection)
        {
            try
            {
                _repository.DeleteRoom(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View("DeleteRoom", id);
            }
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RB_PetHotel</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RB_PetHotel.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RB_PetHotel</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Owner" asp-action="Index">Owners</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pet" asp-action="Index">Pets</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PetRoom" asp-action="Index">Book Date</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Room" asp-action="Index">Rooms</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Service" asp-action="Index">Services</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - RB_PetHotel - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>